import { PrismaService } from 'prisma/prisma.service';
import { Prisma } from 'src/generated/prisma/client';

const badges: Prisma.BadgeCreateManyInput[] = [
  {
    key: 'TONE_MASTER',
    title: 'Tone Master',
    subTitle: 'Emotional Resonance',
    icon: 'psychology',
    variant: 'tertiary',
    criteriaType: 'category_score',
    criteriaConfig: { category: 'Tone', threshold: 90, minSessions: 5 },
  },
  {
    key: 'GRAMMAR_EXPERT',
    title: 'Grammar Expert',
    subTitle: 'Perfect Syntax',
    icon: 'verified',
    variant: 'secondary',
    criteriaType: 'category_score',
    criteriaConfig: { category: 'Grammar', threshold: 95, minSessions: 5 },
  },
  {
    key: 'CLARITY_CHAMPION',
    title: 'Clarity Champion',
    subTitle: 'Crystal Clear Writing',
    icon: 'lightbulb',
    variant: 'primary',
    criteriaType: 'category_score',
    criteriaConfig: { category: 'Clarity', threshold: 90, minSessions: 5 },
  },
  {
    key: 'STRUCTURE_ARCHITECT',
    title: 'Structure Architect',
    subTitle: 'Well Organized',
    icon: 'account_tree',
    variant: 'secondary',
    criteriaType: 'category_score',
    criteriaConfig: { category: 'Structure', threshold: 90, minSessions: 5 },
  },
  {
    key: 'CONCISENESS_KING',
    title: 'Conciseness King',
    subTitle: 'Efficient Writing',
    icon: 'compress',
    variant: 'primary',
    criteriaType: 'category_score',
    criteriaConfig: { category: 'Conciseness', threshold: 90, minSessions: 5 },
  },
  {
    key: 'ETIQUETTE_PRO',
    title: 'Etiquette Pro',
    subTitle: 'Professional Communicator',
    icon: 'handshake',
    variant: 'tertiary',
    criteriaType: 'category_score',
    criteriaConfig: { category: 'Etiquette', threshold: 90, minSessions: 5 },
  },
  {
    key: 'RISING_STAR',
    title: 'Rising Star',
    subTitle: 'Average score above 80',
    icon: 'star',
    variant: 'primary',
    criteriaType: 'overall_score',
    criteriaConfig: { threshold: 80, minSessions: 10 },
  },
  {
    key: 'GOLD_WRITER',
    title: 'Gold Writer',
    subTitle: 'Average score above 90',
    icon: 'workspace_premium',
    variant: 'secondary',
    criteriaType: 'overall_score',
    criteriaConfig: { threshold: 90, minSessions: 15 },
  },
  {
    key: 'MAIL_MENTOR',
    title: 'Mail Mentor',
    subTitle: 'Average score above 95',
    icon: 'military_tech',
    variant: 'tertiary',
    criteriaType: 'overall_score',
    criteriaConfig: { threshold: 95, minSessions: 20 },
  },
  {
    key: 'FIRST_LETTER',
    title: 'First Letter',
    subTitle: 'Complete your first session',
    icon: 'mail',
    variant: 'primary',
    criteriaType: 'session_count',
    criteriaConfig: { sessions: 1 },
  },
  {
    key: 'DEDICATED_WRITER',
    title: 'Dedicated Writer',
    subTitle: 'Complete 25 sessions',
    icon: 'edit_document',
    variant: 'secondary',
    criteriaType: 'session_count',
    criteriaConfig: { sessions: 25 },
  },
  {
    key: 'PROLIFIC_AUTHOR',
    title: 'Prolific Author',
    subTitle: 'Complete 50 sessions',
    icon: 'library_books',
    variant: 'tertiary',
    criteriaType: 'session_count',
    criteriaConfig: { sessions: 50 },
  },
  {
    key: 'CENTURION',
    title: 'Centurion',
    subTitle: 'Complete 100 sessions',
    icon: 'emoji_events',
    variant: 'secondary',
    criteriaType: 'session_count',
    criteriaConfig: { sessions: 100 },
  },
  {
    key: 'THREE_DAY_STREAK',
    title: 'Getting Started',
    subTitle: '3-day practice streak',
    icon: 'local_fire_department',
    variant: 'primary',
    criteriaType: 'streak',
    criteriaConfig: { days: 3 },
  },
  {
    key: 'WEEKLY_WARRIOR',
    title: 'Weekly Warrior',
    subTitle: '7-day practice streak',
    icon: 'whatshot',
    variant: 'secondary',
    criteriaType: 'streak',
    criteriaConfig: { days: 7 },
  },
  {
    key: 'UNSTOPPABLE',
    title: 'Unstoppable',
    subTitle: '30-day practice streak',
    icon: 'bolt',
    variant: 'tertiary',
    criteriaType: 'streak',
    criteriaConfig: { days: 30 },
  },
  {
    key: 'QUICK_LEARNER',
    title: 'Quick Learner',
    subTitle: 'Improve overall score by 10 points',
    icon: 'trending_up',
    variant: 'primary',
    criteriaType: 'improvement',
    criteriaConfig: { increase: 10 },
  },
  {
    key: 'COMEBACK_KID',
    title: 'Comeback Kid',
    subTitle: 'Improve overall score by 20 points',
    icon: 'rocket_launch',
    variant: 'secondary',
    criteriaType: 'improvement',
    criteriaConfig: { increase: 20 },
  },
  {
    key: 'PERFECTIONIST',
    title: 'Perfectionist',
    subTitle: 'Earn a perfect score',
    icon: 'diamond',
    variant: 'tertiary',
    criteriaType: 'perfect_score',
    criteriaConfig: { score: 100 },
  },
];

export async function seedBadge(prisma: PrismaService) {
  await prisma.badge.createMany({
    data: badges,
    skipDuplicates: true,
  });
}
